package com.xworkz.collection.Runner;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.xworkz.collection.dto.MlaDTO;

public class MlaRunner {

	public static void main(String[] args) {

		MlaDTO mla = new MlaDTO("Shashikala jolle", 53, "Nippani", "BJP", false, "Female");
		MlaDTO mla1 = new MlaDTO("Ganesh Hukkeri", 54, "Chikkodi", "BJP", false, "Male");
		MlaDTO mla2 = new MlaDTO("Mahesh Kumathalli", 64, "Athani", "BJP", false, "Male");
		MlaDTO mla3 = new MlaDTO("Srimant patil", 64, "Kagwad", "BJP", false, "Male");
		MlaDTO mla4 = new MlaDTO("P. Rajeev", 45, "Kudachi", "BJP", false, "Male");
		MlaDTO mla5 = new MlaDTO("Duryodhan aihole", 83, "Raibag", "BJP", false, "Male");
		MlaDTO mla6 = new MlaDTO("Umesh katti", 61, "Hukkeri", "BJP", false, "Male");
		MlaDTO mla7 = new MlaDTO("Balachandra jarkiholi", 56, "Arabhavi", "BJP", false, "Male");
		MlaDTO mla8 = new MlaDTO("Ramesh jarkiholi", 62, "Gokak", "BJP", false, "Male");
		MlaDTO mla9 = new MlaDTO("Satish jarkiholi", 60, "yemakanmaradi", "INC", true, "Male");
		MlaDTO mla10 = new MlaDTO("Anil benaka", 27, "Belagavi hatti", "BJP", false, "Male");
		MlaDTO mla11 = new MlaDTO("Abhay patil", 54, "Belagavi dakshin", "BJP", false, "Male");
		MlaDTO mla12 = new MlaDTO("Laxmi hebbalkar", 47, "Belagavi rural", "INC", true, "feMale");
		MlaDTO mla13 = new MlaDTO("Anjali nimbalkar", 46, "Khanapur", "INC", false, "feMale");
		MlaDTO mla14 = new MlaDTO("D.M Basavantary", 62, "Kitturu", "BJP", false, "Male");
		MlaDTO mla15 = new MlaDTO("Mahesh kaujilgi", 61, "Bailongal", "INC", false, "Male");
		MlaDTO mla16 = new MlaDTO("Mahadevappa yadwad", 107, "Ramdurg", "BJP", false, "Male");
		MlaDTO mla17 = new MlaDTO("Govind karjol", 72, "Mudhol", "BJP", false, "Male");
		MlaDTO mla18 = new MlaDTO("Siddu savadi", 63, "Terdal", "BJP", false, "Male");
		MlaDTO mla19 = new MlaDTO("Anand nayamgouda", 53, "Jamkandi", "INC", false, "Male");
		MlaDTO mla20 = new MlaDTO("Murgesh nirani", 57, "Bilagi", "BJP", false, "Male");
		MlaDTO mla21 = new MlaDTO("Siddaramahiah", 75, "Badami", "INC", false, "Male");
		MlaDTO mla22 = new MlaDTO("Veerabhadrayya charantimat", 64, "Bagalkot", "BJP", false, "Male");
		MlaDTO mla23 = new MlaDTO("Doddangowda patil", 87, "Hunagund", "BJP", false, "Male");
		MlaDTO mla24 = new MlaDTO("A.S Patil ", 73, "Muddebhihal", "BJP", false, "Male");
		MlaDTO mla25 = new MlaDTO("Somanagowda patil", 48, "Devara Hipparagi", "BJP", false, "Male");
		MlaDTO mla26 = new MlaDTO("Shivanand patil", 73, "Basawana bhagevadi", "BJP", false, "Male");
		MlaDTO mla27 = new MlaDTO("M.B.Patil", 58, "Babaleshwar", "INC", false, "Male");
		MlaDTO mla28 = new MlaDTO("Basangowda patil yatnal", 59, "Bijapur city", "BJP", false, "Male");
		MlaDTO mla29 = new MlaDTO("Devanand chavan", 52, "Nagtan", "BJP", false, "Male");
		MlaDTO mla30 = new MlaDTO("Y.V.Patil", 87, "Indi", "INC", false, "Male");
		MlaDTO mla31 = new MlaDTO("Bhusanur ramesh balappa", 63, "Sindagi", "BJP", false, "Male");
		MlaDTO mla32 = new MlaDTO("M. y. patil", 84, "Afzalpur", "INC", false, "Male");
		MlaDTO mla33 = new MlaDTO("Ajay Dharam sing", 49, "Javaragi", "INC", false, "Male");
		MlaDTO mla34 = new MlaDTO("Narasimhanayak ", 67, "Shorapur", "BJP", false, "Male");
		MlaDTO mla35 = new MlaDTO("Sharanabasappa goudar", 63, "Shahapur", "INC", false, "Male");
		MlaDTO mla36 = new MlaDTO("Venkatreddy mudhol", 57, "Yadagiri", "BJP", false, "Male");
		MlaDTO mla37 = new MlaDTO("Naganagowda kandukur", 61, "Gurumitakal", "JDS", false, "Male");
		MlaDTO mla38 = new MlaDTO("Priyank kharge", 44, "chittapur", "INC", false, "Male");
		MlaDTO mla39 = new MlaDTO("Rajkumar patil", 45, "sedam", "BJP", false, "Male");
		MlaDTO mla40 = new MlaDTO("Avinash jadav", 41, "chincholi", "BJP", false, "Male");
		MlaDTO mla41 = new MlaDTO("Bsavaraj Muttimud", 41, "Gulbarga rural", "BJP", false, "Male");
		MlaDTO mla42 = new MlaDTO("Dattatraya patil", 49, "Gulbarga dakshin", "BJP", false, "Male");
		MlaDTO mla43 = new MlaDTO("Kaneez fatima", 67, "Gulbarga uttar", "INC", false, "Female");
		MlaDTO mla44 = new MlaDTO("Gttedar subhash tukmayya", 58, " Aland", "BJP", false, "Male");
		MlaDTO mla45 = new MlaDTO("Sharanu salagar", 40, "Basavakalyan", "BJP", false, "Male");
		MlaDTO mla46 = new MlaDTO("Rajshekar basavarj patil", 58, "Homnanbad", "INC", false, "Male");
		MlaDTO mla47 = new MlaDTO("Bandeppa kashempur", 68, "Bidar south", "JDS", false, "Male");
		MlaDTO mla48 = new MlaDTO("Rahim khan", 66, "bidar", "INC", false, "Male");
		MlaDTO mla49 = new MlaDTO("Eshwara bhimanna khandere", 57, "Bhalki", "INC", false, "Male");
		MlaDTO mla50 = new MlaDTO("Prabhu chavhan", 55, "Aurad", "BJP", false, "Male");
		MlaDTO mla51 = new MlaDTO("Basangouda daddal", 65, "Raichur rural", "INC", false, "Male");
		MlaDTO mla52 = new MlaDTO("Dr.Shivraj patil s", 87, "Raichur", "JDS", false, "Male");
		MlaDTO mla53 = new MlaDTO("Raja venkatappa nayak", 36, "Manvi", "JDS", false, "Male");
		MlaDTO mla54 = new MlaDTO("Shivangouda naik", 53, "Devadirga", "BJP", false, "Male");
		MlaDTO mla55 = new MlaDTO("D.S.Hoolageri", 61, "Lingasugur", "INC", false, "Male");
		MlaDTO mla56 = new MlaDTO("Venkatro nadagouda", 56, "Sindhanur", "JDS", false, "Male");
		MlaDTO mla57 = new MlaDTO("Basangouda Turvihal", 46, "Masaki", "INC", false, "Male");
		MlaDTO mla58 = new MlaDTO("Amaregouda linganagouda patil", 62, "Kushtagi", "INC", false, "Male");
		MlaDTO mla59 = new MlaDTO("Basavaraj dhadesugar", 61, "Kankagiri", "BJP", false, "Male");
		MlaDTO mla60 = new MlaDTO("Paranna manavalli", 75, "Gangawati", "BJP", false, "Male");
		MlaDTO mla61 = new MlaDTO("Achar halappa basappa", 75, "yelburga", "BJP", false, "Male");
		MlaDTO mla62 = new MlaDTO("K. Ragavendra hitnal", 43, "Koppal", "INC", false, "Male");
		MlaDTO mla63 = new MlaDTO("Ramappa lamani", 58, "Sirahatti", "BJP", false, "Male");
		MlaDTO mla64 = new MlaDTO("H.K.Patil", 73, "Gadag", "INC", false, "Male");
		MlaDTO mla65 = new MlaDTO("Kalakappa Bandi", 49, "Ron", "BJP", false, "Male");
		MlaDTO mla66 = new MlaDTO("C.C.Patil", 79, "Naragund", "BJP", false, "Male");
		MlaDTO mla67 = new MlaDTO("Patil Munenakoppa Shankar", 69, "Navalgund", "BJP", false, "Male");
		MlaDTO mla68 = new MlaDTO("Kusuma Shivalli", 51, "Kundgol", "INC", false, "FeMale");
		MlaDTO mla69 = new MlaDTO("Amrupayyappa desai", 41, "Dharwad", "BJP", false, "Male");
		MlaDTO mla70 = new MlaDTO("Abhayya prasad", 53, "Hubli dharwad-Easte", "INC", false, "Male");
		MlaDTO mla71 = new MlaDTO("Jagadish shettar", 75, "Hubli-Dharwad Central", "BJP", false, "Male");
		MlaDTO mla72 = new MlaDTO("Aravind Bellad", 55, "Hubli Dharwad-west", "BJP", false, "Male");
		MlaDTO mla73 = new MlaDTO("C.N.Nambannavar", 69, "Kalagatgi", "BJP", false, "Male");
		MlaDTO mla74 = new MlaDTO("R.V.Deshapande", 76, "Haliyal", "INC", false, "Male");
		MlaDTO mla75 = new MlaDTO("Roopali naik", 50, "Karwar", "BJP", false, "Female");
		MlaDTO mla76 = new MlaDTO("Dinakar Keshva Sheetty", 65, "Kumta", "BJP", false, "Male");
		MlaDTO mla77 = new MlaDTO("Sunil Biliya naik", 44, "Bhatkal", "BJP", false, "Male");
		MlaDTO mla78 = new MlaDTO("Vishweshwar hegde kageri", 61, "Sirsi", "BJP", false, "Male");
		MlaDTO mla79 = new MlaDTO("Arbail Shivaram Hebbal", 66, "Yellapur", "BJP", false, "Male");
		MlaDTO mla80 = new MlaDTO("Shrinivas mane", 56, "Hungal", "INC", false, "Male");
		MlaDTO mla81 = new MlaDTO("Basavaraj bommai", 63, "Shiggoa", "BJP", false, "Male");
		MlaDTO mla82 = new MlaDTO("Neharu Olekare", 61, "Haveri ", "BJP", false, "Male");
		MlaDTO mla83 = new MlaDTO("Ballary Virupakshappa Rudrappa", 56, "Byadgi", "BJP", false, "Male");
		MlaDTO mla84 = new MlaDTO("B.C.Patil", 56, "Hirekerur", "BJP", false, "Male");
		MlaDTO mla85 = new MlaDTO("Arunkumar Guththur", 65, "Ranibennur", "BJP", false, "Male");
		MlaDTO mla86 = new MlaDTO("P.T.Parameshwar Naik", 56, "Hadagali", "BJP", false, "Male");
		MlaDTO mla87 = new MlaDTO("L.B.P.Bheemanaik", 48, "Hagaribommanahalli", "INC", false, "Male");
		MlaDTO mla88 = new MlaDTO("J.N.Ganesh", 55, "Kampli", "INC", false, "Male");
		MlaDTO mla89 = new MlaDTO("M.S.Somalingappa", 62, "Siraguppa", "BJP", false, "Male");
		MlaDTO mla90 = new MlaDTO("B Nagendra", 53, "Ballary Rural", "INC", false, "Male");
		MlaDTO mla91 = new MlaDTO("G Somashekhar Reddy", 52, "Ballary City", "BJP", false, "Male");
		MlaDTO mla92 = new MlaDTO("E. Thukaram", 56, "Sandur", "INC", false, "Male");
		MlaDTO mla93 = new MlaDTO("N Y GopalKrishnan", 53, "kudligi", "BJP", false, "Male");
		MlaDTO mla94 = new MlaDTO("B SriRamulu", 52, "Molakalmuru", "BJP", false, "Male");
		MlaDTO mla95 = new MlaDTO("T Ragha murthy", 63, "Challakere", "INC", false, "Male");
		MlaDTO mla96 = new MlaDTO("G H Thippareddy", 75, "Chitradurga", "BJP", false, "Male");
		MlaDTO mla97 = new MlaDTO("Purnima Krishnappa", 48, "Hiriyur", "BJP", false, "Female");
		MlaDTO mla98 = new MlaDTO("Gulatti D Shekhar", 49, "Hosadurga", "BJP", false, "Male");
		MlaDTO mla99 = new MlaDTO("M Chandrappa", 65, "Holalkere", "BJP", false, "Male");
		MlaDTO mla100 = new MlaDTO("S V Ramachandra", 53, "Jagaluru", "BJP", false, "Male");
		MlaDTO mla101 = new MlaDTO("G Karunakara Reddy", 55, "Harappanahalli", "BJP", false, "Male");
		MlaDTO mla102 = new MlaDTO("S Ramappa", 54, "Harihara", "INC", false, "Male");
		MlaDTO mla103 = new MlaDTO("S A Ravindranath", 50, "Davanagere North", "BJP", false, "Male");
		MlaDTO mla104 = new MlaDTO("Shamanuru Shivashankarappa", 91, "Davanagere South", "INC", false, "Male");
		MlaDTO mla105 = new MlaDTO("N Ninganna", 53, "Mayakonda", "BJP", false, "Male");
		MlaDTO mla106 = new MlaDTO("K Madal Veerupakshappa", 83, "Vijayanagar", "BJP", false, "Male");
		MlaDTO mla107 = new MlaDTO("M P Renukacharya", 62, "Honnalli", "BJP", false, "Male");
		MlaDTO mla108 = new MlaDTO("K B Ashok Naik", 55, "Shimogga Rural", "BJP", false, "Male");
		MlaDTO mla109 = new MlaDTO("K B Sangameshwara", 59, "Bhadravati", "INC", false, "Male");
		MlaDTO mla110 = new MlaDTO("K S Ishwarappa", 56, "Shimogga", "BJP", false, "Male");
		MlaDTO mla111 = new MlaDTO("Aragha Jananendra", 59, "Theerthahalli", "BJP", false, "Male");
		MlaDTO mla112 = new MlaDTO("B S Yadyurappa", 80, "Shikaripura", "BJP", false, "Male");
		MlaDTO mla113 = new MlaDTO("Kumar Bangarappa", 59, "Soraba", "BJP", false, "Male");
		MlaDTO mla114 = new MlaDTO("Hartalu Halappa", 62, "Sagara", "BJP", false, "Male");
		MlaDTO mla115 = new MlaDTO("B M SukumarShetty", 66, "Bainduru", "BJP", false, "Male");
		MlaDTO mla116 = new MlaDTO("Haladi Shrinivas Shetty", 72, "Kundapura", "BJP", false, "Male");
		MlaDTO mla117 = new MlaDTO("K Raghupati Bhat", 41, "Udupi", "BJP", false, "Male");
		MlaDTO mla118 = new MlaDTO("Lalagimendon", 63, "Kapu", "BJP", false, "Male");
		MlaDTO mla119 = new MlaDTO("V Sunil Kumar", 47, "Karkal", "BJP", false, "Male");
		MlaDTO mla120 = new MlaDTO("T D Rajegouda", 58, "Shringeri", "INC", false, "Male");
		MlaDTO mla121 = new MlaDTO("M P Kumaraswamy", 59, "Mudigere", "BJP", false, "Male");
		MlaDTO mla122 = new MlaDTO("C T Ravi", 63, "Chikkamagaluru", "BJP", false, "Male");
		MlaDTO mla123 = new MlaDTO("D S Suresh", 40, "Tarikere", "BJP", false, "Male");
		MlaDTO mla124 = new MlaDTO("BelliPrakash", 65, "Kadur", "BJP", false, "Male");
		MlaDTO mla125 = new MlaDTO("J C Madhuswamy", 70, "Chikkanayakanhalli", "BJP", false, "Male");
		MlaDTO mla126 = new MlaDTO("B C Nagesh", 63, "Thiptur", "BJP", false, "Male");
		MlaDTO mla127 = new MlaDTO("Jayaram E S", 57, "Thuruvekere", "BJP", false, "Male");
		MlaDTO mla128 = new MlaDTO("Dr. H D Ranganath", 46, "Kunigal", "INC", false, "Male");
		MlaDTO mla129 = new MlaDTO("G B Jyoti Ganesh", 38, "Thumkuru City", "BJP", false, "Female");
		MlaDTO mla130 = new MlaDTO("D C Gouri Shankar", 43, "Thumuru Rural", "JDS", false, "Male");
		MlaDTO mla131 = new MlaDTO("Dr. G Parameshwara", 73, "Koratagere", "INC", false, "Male");
		MlaDTO mla132 = new MlaDTO("C M Rajeshgouda", 50, "Shira", "BJP", false, "Male");
		MlaDTO mla133 = new MlaDTO("Venkataramappa", 69, "Pavagada", "INC", false, "Male");
		MlaDTO mla134 = new MlaDTO("M V Veerabhadrayya", 63, "Madhugiri", "JDS", false, "Male");
		MlaDTO mla135 = new MlaDTO("N H ShivaShankara Reddy", 73, "Gouri Bidanuru", "INC", false, "Male");
		MlaDTO mla136 = new MlaDTO("S N SubbaReddy", 56, "Bagepalli", "INC", false, "Male");
		MlaDTO mla137 = new MlaDTO("K Sudhakar", 49, "Chikkaballapura", "BJP", false, "Male");
		MlaDTO mla138 = new MlaDTO("V Muniyappa", 75, "Sidlaghatta", "INC", false, "Male");
		MlaDTO mla139 = new MlaDTO("J K Krishna Reddy", 55, "Chintamani", "JDS", false, "Male");
		MlaDTO mla140 = new MlaDTO("K K Ramesh Kumar", 57, "Shreenivasapura", "INC", false, "Male");
		MlaDTO mla141 = new MlaDTO("H Nagesh", 64, "Mulbagilu", "INC", false, "Male");
		MlaDTO mla142 = new MlaDTO("M Rupakala", 38, "Kolara Goldfield", "INC", false, "Female");
		MlaDTO mla143 = new MlaDTO("S N Narayana Swamy", 45, "Bangarpete", "INC", false, "Male");
		MlaDTO mla144 = new MlaDTO("K Shinivasagouda", 65, "Kolar", "INC", false, "Male");
		MlaDTO mla145 = new MlaDTO("K Y Nanjegouda", 61, "Maluru", "INC", false, "Male");
		MlaDTO mla146 = new MlaDTO("S R Vishwanath", 60, "Yalahanka", "BJP", false, "Male");
		MlaDTO mla147 = new MlaDTO("Byrathi Basavaraj", 59, "K R Pura", "BJP", false, "Male");
		MlaDTO mla148 = new MlaDTO("Krishna Bairegouda", 45, "Bythrayanapura", "INC", false, "Male");
		MlaDTO mla149 = new MlaDTO("S D Somashekhar", 47, "Yashvanthpura", "BJP", false, "Male");
		MlaDTO mla150 = new MlaDTO("Munirathna", 58, "RR Nagar", "BJP", false, "Male");
		MlaDTO mla151 = new MlaDTO("R Manjunath", 59, "Dasarahalli", "JDS", false, "Male");
		MlaDTO mla152 = new MlaDTO("K Gopalayya", 62, "Mahalaxmi layout", "BJP", false, "Male");
		MlaDTO mla153 = new MlaDTO("Dr. C N Ashwath Narayan", 55, "Malleshwaram", "BJP", false, "Male");
		MlaDTO mla154 = new MlaDTO("Byrathi Suresh", 50, "Hebbal", "INC", false, "Male");
		MlaDTO mla155 = new MlaDTO("Akhanda Shinivasamurthy", 64, "Pulikeshi Nagara", "INC", false, "Male");
		MlaDTO mla156 = new MlaDTO("K G Georg", 76, "Sarvagnanagar", "INC", false, "Male");
		MlaDTO mla157 = new MlaDTO("S Raghu", 48, "C V Raman Nagar", "BJP", false, "Male");
		MlaDTO mla158 = new MlaDTO("Rizwan Arshad", 43, "Shivaji nagar", "INC", false, "Male");
		MlaDTO mla159 = new MlaDTO("N A Harish", 56, "Shantinagar", "INC", false, "Male");
		MlaDTO mla160 = new MlaDTO("Dinesh Gundurav", 53, "Gandhinagar", "INC", false, "Male");
		MlaDTO mla161 = new MlaDTO("S.Suresh Kumar", 67, "Rajajinagar", "BJP", false, "Male");
		MlaDTO mla162 = new MlaDTO("V.Somanna", 72, "Govindaraj nagar", "BJP", false, "Male");
		MlaDTO mla163 = new MlaDTO("M. Krishnappa", 70, "VijayNagar", "BJP", false, "Male");
		MlaDTO mla164 = new MlaDTO("Zameer Ahmed Khan", 56, "Chamrajpet", "INC", false, "Male");
		MlaDTO mla165 = new MlaDTO("Uday B garudachar", 63, "Chickpet", "BJP", false, "Male");
		MlaDTO mla166 = new MlaDTO("L.A.Ravi Subramanya", 64, "Basavanagudi", "BJP", false, "Male");
		MlaDTO mla167 = new MlaDTO("R Ashoka", 65, "Padmanaba Nagar", "BJP", false, "Male");
		MlaDTO mla168 = new MlaDTO("Ramalinga Reddy", 69, "B.T.M.Layout", "INC", false, "Male");
		MlaDTO mla169 = new MlaDTO("Soumya Reddy", 40, "Jayanagar", "INC", false, "Male");
		MlaDTO mla170 = new MlaDTO("Aravind Limbavali", 56, "Mahadevapura", "BJP", false, "Male");
		MlaDTO mla171 = new MlaDTO("M.Krishnappa", 70, "Banglore South", "BJP", false, "Male");
		MlaDTO mla172 = new MlaDTO("B.Shivanna", 56, "Anekal", "INC", false, "Male");
		MlaDTO mla173 = new MlaDTO("Shrath Kumar Bachegowda", 41, "Hoskote", "INC", false, "Male");
		MlaDTO mla174 = new MlaDTO("Nisarga Narayanaswamy L.N", 53, "Devanhalli", "JDS", false, "Male");
		MlaDTO mla175 = new MlaDTO("T.Venkataramanaiah", 65, "Doddaballapur", "INC", false, "Male");
		MlaDTO mla176 = new MlaDTO("Dr.K.Srinavasamurthy", 73, "Nelemangala", "JDS", false, "Male");
		MlaDTO mla177 = new MlaDTO("A.Manjunath", 48, "Magadi", "JDS", false, "Male");
		MlaDTO mla178 = new MlaDTO("Anita Kumaraswami", 63, "Ramanagar", "JDS", false, "Female");
		MlaDTO mla179 = new MlaDTO("D.K.Shivukumar", 60, "Kanakapura", "INC", false, "Male");
		MlaDTO mla180 = new MlaDTO("H.D.Kumaraswamy", 63, "Channapatna", "JDS", false, "Male");
		MlaDTO mla181 = new MlaDTO("Dr.K.Annadani", 69, "Malavalli", "BJP", false, "Male");
		MlaDTO mla182 = new MlaDTO("D.C.Thamanna", 80, "Maddur", "JDS", false, "Male");
		MlaDTO mla183 = new MlaDTO("C.S.Puttaraju", 58, "Melukote", "BJP", false, "Male");
		MlaDTO mla184 = new MlaDTO("M.Srinivas", 80, "Mandya", "JDS", false, "Male");
		MlaDTO mla185 = new MlaDTO("Ravindra Srikantaaih", 51, "Shrirangapatanam", "JDS", false, "Male");
		MlaDTO mla186 = new MlaDTO("Suresh Gowda", 72, "Nagamangala", "JDS", false, "Male");
		MlaDTO mla187 = new MlaDTO("Narayana Gowda", 55, "Krishnarajpere", "BJP", false, "Male");
		MlaDTO mla188 = new MlaDTO("C.N.Balakrishna", 49, "Shravanbelegola", "JDS", false, "Male");
		MlaDTO mla189 = new MlaDTO("K.M.Shivalingegowda", 65, "Arasikere", "INC", false, "Male");
		MlaDTO mla190 = new MlaDTO("K.S.Lingesha", 59, "BELUR", "JDS", false, "Male");
		MlaDTO mla191 = new MlaDTO("Preetham J.Gowda", 41, "Hasan", "BJP", false, "Male");
		MlaDTO mla192 = new MlaDTO("H.D.Revanna", 65, "Holenarasipur", "JDS", false, "Male");
		MlaDTO mla193 = new MlaDTO("H.K.Kumaraswamy", 67, "Sakaleshpura", "JDS", false, "Male");
		MlaDTO mla194 = new MlaDTO("Harish Poonja", 40, "Belthangadi", "BJP", false, "Male");
		MlaDTO mla195 = new MlaDTO("Umanantha A.Kotian", 62, "Moodabidari", "BJP", false, "Male");
		MlaDTO mla196 = new MlaDTO("Bharath Shetty", 51, "Manglore City north", "BJP", false, "Male");
		MlaDTO mla197 = new MlaDTO("D.Vedavyad Kamath", 45, "Manglore City South", "BJP", false, "Male");
		MlaDTO mla198 = new MlaDTO("U.T.Khadekar", 53, "Manglore", "INC", false, "Male");
		MlaDTO mla199 = new MlaDTO("Rajesh Naik", 64, "Bantval", "BJP", false, "Male");
		MlaDTO mla200 = new MlaDTO("Sanjeeva Matandoor", 61, "Puttur", "BJP", false, "Male");
		MlaDTO mla201 = new MlaDTO("Angara S", 58, "Sullia", "BJP", false, "Male");
		MlaDTO mla202 = new MlaDTO("Appachu Ranjan", 65, "Madikeri", "BJP", false, "Male");
		MlaDTO mla203 = new MlaDTO("K.G.Bopaiah", 67, "Vijayapet", "BJP", false, "Male");
		MlaDTO mla204 = new MlaDTO("K.Mahadeva", 67, "Periyapatna", "JDS", false, "Male");
		MlaDTO mla205 = new MlaDTO("S.R.Mahesh", 65, "Krishnarajanagar", "JDS", false, "Male");
		MlaDTO mla206 = new MlaDTO("H.P.Manjunatha", 55, "Hunsur", "INC", false, "Male");
		MlaDTO mla207 = new MlaDTO("Anilkumar C", 41, "Heggadedevankote", "INC", false, "Male");
		MlaDTO mla208 = new MlaDTO("Harshavardhan B.", 46, "Nanjangudu", "BJP", false, "Male");
		MlaDTO mla209 = new MlaDTO("G.T.Devegowda", 63, "Chamundeshwari", "JDS", false, "Male");
		MlaDTO mla210 = new MlaDTO("S.A.Ramadas", 63, "Krishnaraja", "BJP", false, "Male");
		MlaDTO mla211 = new MlaDTO("L.Nagendra", 59, "Chamaraja", "BJP", false, "Male");
		MlaDTO mla212 = new MlaDTO("Tanveer Sait", 55, "Narasimharaja", "BJP", false, "Male");
		MlaDTO mla213 = new MlaDTO("Yathindra S", 42, "Varuna", "INC", false, "Male");
		MlaDTO mla214 = new MlaDTO("Ashwin Kumara M", 31, "T.Narasipura", "JDS", false, "Male");
		MlaDTO mla215 = new MlaDTO("R.Narendra", 56, "Hanur", "INC", false, "Male");
		MlaDTO mla216 = new MlaDTO("N.Mahesh", 66, "Kollegala", "BJP", false, "Male");
		MlaDTO mla217 = new MlaDTO("C.Puttarangashetty", 68, "Chamarajnagara", "INC", false, "Male");
		MlaDTO mla218 = new MlaDTO("C.S.Niranjankumar", 49, "Gundlupete", "BJP", false, "Male");
		MlaDTO mla219 = new MlaDTO("A.T.Ramaswami", 71, "Arakalgud", "BJP", false, "Male");
		MlaDTO mla220 = new MlaDTO("Naganagowda Kundukar", 67, "Gurmitkal", "JDS", false, "Male");
		MlaDTO mla221 = new MlaDTO("N.Y.Gopalakrishnan", 70, "Kudlgi", "BJP", false, "Male");
		MlaDTO mla222 = new MlaDTO("A.T.Ramaswamy", 71, "Arkalgud", "JDS", false, "Male");
		MlaDTO mla223 = new MlaDTO("Vinisha Nero", 46, "Anglo-Indian", "BJP", false, "Female");

		List<MlaDTO> list = new ArrayList<>();
		list.add(mla);
		list.add(mla1);
		list.add(mla2);
		list.add(mla3);
		list.add(mla4);
		list.add(mla5);
		list.add(mla6);
		list.add(mla7);
		list.add(mla8);
		list.add(mla9);
		list.add(mla10);
		list.add(mla11);
		list.add(mla12);
		list.add(mla13);
		list.add(mla14);
		list.add(mla15);
		list.add(mla16);
		list.add(mla17);
		list.add(mla18);
		list.add(mla19);
		list.add(mla20);
		list.add(mla21);
		list.add(mla22);
		list.add(mla23);
		list.add(mla24);
		list.add(mla25);
		list.add(mla26);
		list.add(mla27);
		list.add(mla28);
		list.add(mla29);
		list.add(mla30);
		list.add(mla31);
		list.add(mla32);
		list.add(mla33);
		list.add(mla34);
		list.add(mla35);
		list.add(mla36);
		list.add(mla37);
		list.add(mla38);
		list.add(mla39);
		list.add(mla40);
		list.add(mla41);
		list.add(mla42);
		list.add(mla43);
		list.add(mla44);
		list.add(mla45);
		list.add(mla46);
		list.add(mla47);
		list.add(mla48);
		list.add(mla49);
		list.add(mla50);
		list.add(mla51);
		list.add(mla52);
		list.add(mla53);
		list.add(mla54);
		list.add(mla55);
		list.add(mla56);
		list.add(mla57);
		list.add(mla58);
		list.add(mla59);
		list.add(mla60);
		list.add(mla61);
		list.add(mla62);
		list.add(mla63);
		list.add(mla64);
		list.add(mla65);
		list.add(mla66);
		list.add(mla67);
		list.add(mla68);
		list.add(mla69);
		list.add(mla70);
		list.add(mla71);
		list.add(mla72);
		list.add(mla73);
		list.add(mla74);
		list.add(mla75);
		list.add(mla76);
		list.add(mla77);
		list.add(mla78);
		list.add(mla79);
		list.add(mla80);
		list.add(mla81);
		list.add(mla82);
		list.add(mla83);
		list.add(mla84);
		list.add(mla85);
		list.add(mla86);
		list.add(mla87);
		list.add(mla88);
		list.add(mla89);
		list.add(mla90);
		list.add(mla91);
		list.add(mla92);
		list.add(mla93);
		list.add(mla94);
		list.add(mla95);
		list.add(mla96);
		list.add(mla97);
		list.add(mla98);
		list.add(mla99);
		list.add(mla100);
		list.add(mla101);
		list.add(mla102);
		list.add(mla103);
		list.add(mla104);
		list.add(mla105);
		list.add(mla106);
		list.add(mla107);
		list.add(mla108);
		list.add(mla109);
		list.add(mla110);
		list.add(mla111);
		list.add(mla112);
		list.add(mla113);
		list.add(mla114);
		list.add(mla115);
		list.add(mla116);
		list.add(mla117);
		list.add(mla118);
		list.add(mla119);
		list.add(mla120);
		list.add(mla121);
		list.add(mla122);
		list.add(mla123);
		list.add(mla124);
		list.add(mla125);
		list.add(mla126);
		list.add(mla127);
		list.add(mla128);
		list.add(mla129);
		list.add(mla130);
		list.add(mla131);
		list.add(mla132);
		list.add(mla133);
		list.add(mla134);
		list.add(mla135);
		list.add(mla136);
		list.add(mla137);
		list.add(mla138);
		list.add(mla139);
		list.add(mla140);
		list.add(mla141);
		list.add(mla142);
		list.add(mla143);
		list.add(mla144);
		list.add(mla145);
		list.add(mla146);
		list.add(mla147);
		list.add(mla148);
		list.add(mla149);
		list.add(mla150);
		list.add(mla151);
		list.add(mla152);
		list.add(mla153);
		list.add(mla154);
		list.add(mla155);
		list.add(mla156);
		list.add(mla157);
		list.add(mla158);
		list.add(mla159);
		list.add(mla160);
		list.add(mla161);
		list.add(mla162);
		list.add(mla163);
		list.add(mla164);
		list.add(mla165);
		list.add(mla166);
		list.add(mla167);
		list.add(mla168);
		list.add(mla169);
		list.add(mla170);
		list.add(mla171);
		list.add(mla172);
		list.add(mla173);
		list.add(mla174);
		list.add(mla175);
		list.add(mla176);
		list.add(mla177);
		list.add(mla178);
		list.add(mla179);
		list.add(mla180);
		list.add(mla181);
		list.add(mla182);
		list.add(mla183);
		list.add(mla184);
		list.add(mla185);
		list.add(mla186);
		list.add(mla187);
		list.add(mla188);
		list.add(mla189);
		list.add(mla190);
		list.add(mla191);
		list.add(mla192);
		list.add(mla193);
		list.add(mla194);
		list.add(mla195);
		list.add(mla196);
		list.add(mla197);
		list.add(mla198);
		list.add(mla199);
		list.add(mla200);
		list.add(mla201);
		list.add(mla202);
		list.add(mla203);
		list.add(mla204);
		list.add(mla205);
		list.add(mla206);
		list.add(mla207);
		list.add(mla208);
		list.add(mla209);
		list.add(mla210);
		list.add(mla211);
		list.add(mla212);
		list.add(mla213);
		list.add(mla214);
		list.add(mla215);
		list.add(mla216);
		list.add(mla217);
		list.add(mla218);
		list.add(mla219);
		list.add(mla220);
		list.add(mla221);
		list.add(mla222);
		list.add(mla223);

//		list.add(new MlaDTO(null, 0, null, null, false, null));  implicit//

		System.out.println("total mla list:" + list.size());

		System.err.println("*****************MLA'S is grater than 50************************");

		list.stream().filter(element -> element.getAge() > 50).collect(Collectors.toList())
				.forEach(element -> System.out.println(element));

		System.err.println("*********MLA's is lesser than 50************");
		list.stream().filter(e -> e.getAge() < 50).collect(Collectors.toList()).forEach(e -> System.out.println(e));

		System.err.println("*************Female mla****************");
		list.stream().filter(e -> e.getGender().contains("Female")).collect(Collectors.toList())
				.forEach(e -> System.out.println(e));

		System.err.println("**************Male MLA*********************");
		list.stream().filter(element -> element.getGender().contains("Male")).collect(Collectors.toList())
				.forEach(element -> System.out.println(element));

		System.out.println("***************Collect all mls by party********************");
		list.stream().filter(e -> e.getParty().contains("BJP")).collect(Collectors.toList())
				.forEach(e -> System.out.println(e));

		System.out.println("==================JDS==================");
		list.stream().filter(element -> element.getParty().contains("JDS")).collect(Collectors.toList())
				.forEach(element -> System.out.println(element));

		System.err.println("***********get age grater than 50& party******************");
		list.stream().filter(e -> e.getAge() > 50 && e.getParty().contains("BJP")).collect(Collectors.toList())
				.forEach(e -> System.out.println(e));

		System.err.println("*****************Independent partys*************");
		list.stream().filter(e -> e.isIndependent()).collect(Collectors.toList()).forEach(e -> System.out.println(e));

		System.err.println("***************Unique party***********");
		list.stream().map(e->e.getParty()).collect(Collectors.toSet()).forEach(e->System.out.println(e));
		
		System.err.println("*********sorted collection byparty name in ascending order******");
		list.stream().sorted((ref1,ref2)->ref1.getParty().compareTo(ref2.getParty())).forEach(ref->System.out.println(ref));
		
		System.err.println("************sorted collection in descending order***************");
		list.stream().sorted((ref2,ref1)->ref2.getName().compareTo(ref1.getName())).forEach(ref->System.out.println(ref));
	
		System.err.println("*****sorted collection by age in descender order*************");
		list.stream().sorted((element2,element1)->Double.compare(element2.getAge(), element1.getAge())).forEach(element->System.out.println(element));
	}
}
